### ISSUE TITLE
odd rendering with pushWithValues

### ISSUE THREAD

**Issue by joprice** [dagronf/DSFSparkline#3]
Using `pushWithValues` with a `windowSize` smaller than the size of the values causes the values to be collected to the right of the sparkline. `setWithValues`, whereas renders as expected. It seems like I'm misusing `pushWithValues`.

**Comment by joprice** [comment]
I'm also seeing lines overlapping one another when pushing new values:

<img width="401" alt="Screen Shot 2021-01-30 at 11 01 30 PM" src="https://user-images.githubusercontent.com/2175555/106374242-22a90300-634f-11eb-9c4a-edf8f8d5e09c.png">

**Comment by joprice** [comment]
The plot thickens: I tried testing if updating the sparkline with a separate dataset on each tap would work, testing it with an array with a single element `[_dataSource setWithValues:@[@1]];`, but I got a crash with an assertion failure:  `Assertion failed: file DSFSparkline/CGPath+Hermite.swift, line 52`

**Comment by dagronf** [comment]
Hey mate - sorry to hear you're having issues.  

All of the demo apps use the standard 'push' mechanism for adding data to the graph for example, in the macOS Sparkline Demo Objc it uses `[[self receiveDataSource] pushWithValue:v1];` in ViewController.m.

I also checked what happens if you try to `setWithValues` with a data size greater than the window size. The code handles this scenario by truncating the input data (https://github.com/dagronf/DSFSparkline/blob/4762e0865e4b50eb4b495eb9ac81add5a258cd85/Sources/DSFSparkline/private/core/SparklineWindow.swift#L121)

I'm guessing the issue you're seeing is elsewhere. I did fix an issue a little while back (which hasn't made its way into a release yet) which relates to how the background of the control is drawn (I'd forgotten to set the `isOpaque. This might fix the overdrawing issue you see above.

1. Which version of the library are you using?
2. Which OS are building for? iOS 13 etc
3. Xcode version? 
4. Swift or Objective-C? (shouldn't matter but lets try narrow it down)

Even better - Is it possible to send me a simple project that displays this issue?  I guessing you're using iOS (you mention tap so I'm guessing here).

If I can reproduce the issue with your data then I'll be able to fix it much quicker.

Cheers and thanks -- Darren.

**Comment by dagronf** [comment]
I've pushed the iOS opacity flag fix and a guard against the crash you've mentioned into a 3.3.0 release if you're interested in seeing if they were the cause of your issues.

**Comment by joprice** [comment]
Thanks! I'll try it out in a bit. I'm building from source using bazel, so I can grab the master branch any time. Let me try to repro again with your fixes to make sure it's still happening.

**Comment by dagronf** [comment]
Hey there @joprice, Have you had a chance to verify whether this issue still occurs on master?

**Comment by joprice** [comment]
I'm not able to repro the issues I was having. Thank you for the quick fixes!

**Comment by dagronf** [comment]
Ah that's good news mate. Thanks for your feedback and input!
